-- Generated by scripts/generate-seed.mjs — do not edit by hand.
DELETE FROM fd_content_block;
DELETE FROM fd_module;
DELETE FROM fd_brand;
DELETE FROM fd_access_code;
INSERT INTO fd_brand (slug, name, tokens_json, voice_json, created_at) VALUES ('omnissa', 'Omnissa', '{"color":{"bg":"#F5F5F7","surface":"#FFFFFF","ink":"#28334A","ink-strong":"#001E60","muted":"#616899","accent":"#4A12F0","on-accent":"#FFFFFF","signal":"#C9FF27","on-signal":"#001E60","line":"#D9D9E4","line-strong":"#B6B9D0","danger":"#B02A37","success":"#146C43"},"fontDisplay":"''Outfit Variable'', ''Outfit'', sans-serif","fontBody":"''Outfit Variable'', ''Outfit'', sans-serif","fontUtility":"''IBM Plex Mono'', ui-monospace, monospace","radius":"6px","logoUrl":""}', '{"greeting":"Built for how People teams actually work.","signoff":"Independent demonstration. Not affiliated with or endorsed by Omnissa."}', '2026-08-07T01:43:11.488Z');
INSERT INTO fd_brand (slug, name, tokens_json, voice_json, created_at) VALUES ('verdant', 'Verdant Collective', '{"color":{"bg":"#F2F4EF","surface":"#FBFCF9","ink":"#25332B","ink-strong":"#152219","muted":"#5E7266","accent":"#2F6B4F","on-accent":"#FFFFFF","signal":"#FFB84D","on-signal":"#152219","line":"#D4DCD2","line-strong":"#AFBDB1","danger":"#A33B2E","success":"#2F6B4F"},"fontDisplay":"Georgia, ''Times New Roman'', serif","fontBody":"-apple-system, ''Segoe UI'', system-ui, sans-serif","fontUtility":"''Courier New'', ui-monospace, monospace","radius":"14px","logoUrl":""}', '{"greeting":"Grow judgment, not just skills.","signoff":"Verdant Collective is a fictional brand used to prove the theming system."}', '2026-08-07T01:43:11.488Z');
INSERT INTO fd_access_code (id, brand_slug, code_hash, label, max_uses, uses, expires_at, active) VALUES ('2fa0ed91-82e9-4dbe-864d-c508095e783a', 'omnissa', 'pbkdf2$100000$rdpiB8zS94DTkMvGtSDuEw==$KGyZ9/2Fw4JjGjOvszTtGn/g1RIo6kFJq4JOJ7/tz5M=', 'Reviewer 1 · Omnissa', NULL, 0, NULL, 1);
INSERT INTO fd_access_code (id, brand_slug, code_hash, label, max_uses, uses, expires_at, active) VALUES ('ea3dc9fd-da00-4d5c-86d2-e4deccecd6e5', 'verdant', 'pbkdf2$100000$MdFQHVR8sUf0rpvYPTYHow==$+aXxfajPAAOK7YZINAKLf9EhfgULPZBTISjIobpunXs=', 'Theming proof', NULL, 0, NULL, 1);
INSERT INTO fd_module (id, course_id, ordinal, title, blurb, status, est_minutes, prereq_json) VALUES ('ai101-m1', 'ai101', 1, 'What is AI?', 'A working mental model: what an LLM actually does, the vocabulary, why data decides everything, and a delegation heuristic you can carry under pressure.', 'open', 30, NULL);
INSERT INTO fd_module (id, course_id, ordinal, title, blurb, status, est_minutes, prereq_json) VALUES ('ai101-m2', 'ai101', 2, 'Choosing the tool for the task', 'Chat assistants, copilots, and the AI already embedded in your HR stack — what each is actually for, and how to tell a language model from a scoring engine before you rely on either.', 'locked', 25, NULL);
INSERT INTO fd_module (id, course_id, ordinal, title, blurb, status, est_minutes, prereq_json) VALUES ('ai101-m3', 'ai101', 3, 'What it costs and how it scales', 'Tokens, context windows, and pricing — enough of the economics to size a use case, read a vendor quote, and know when a bigger model is worth it.', 'locked', 25, NULL);
INSERT INTO fd_module (id, course_id, ordinal, title, blurb, status, est_minutes, prereq_json) VALUES ('ai101-m4', 'ai101', 4, 'Working with your documents and data', 'Attachments, long documents, and sensitive material: getting your world into the model''s view without crowding out the question — or crossing a line your legal team hasn''t cleared.', 'locked', 30, NULL);
INSERT INTO fd_module (id, course_id, ordinal, title, blurb, status, est_minutes, prereq_json) VALUES ('ai101-m5', 'ai101', 5, 'Prompting as briefing', 'Role, task, context, format. Prompting as briefing a capable stranger — and iteration as the keystone behavior that separates fluent users from frustrated ones.', 'locked', 35, '["ai101-m1"]');
INSERT INTO fd_module (id, course_id, ordinal, title, blurb, status, est_minutes, prereq_json) VALUES ('ai101-m6', 'ai101', 6, 'When it''s confidently wrong', 'Hallucination in depth: why fluent output deserves more scrutiny, not less, and the verification habits that keep a fabricated citation out of a document with someone''s name on it.', 'locked', 30, '["ai101-m1"]');
INSERT INTO fd_module (id, course_id, ordinal, title, blurb, status, est_minutes, prereq_json) VALUES ('ai101-m7', 'ai101', 7, 'The lines that don''t move', 'Bias, adverse impact, and decisions about people. Where AI assists, where it must stop, and how to say so in a way your organization will actually follow.', 'locked', 30, '["ai101-m6"]');
INSERT INTO fd_module (id, course_id, ordinal, title, blurb, status, est_minutes, prereq_json) VALUES ('ai101-m8', 'ai101', 8, 'What you own', 'Data agreements, disclosure, and accountability. What you''re responsible for when AI touched the work — and the policy questions to settle before someone asks.', 'locked', 25, NULL);
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-brief', 'ai101-m1', 10, 'prose', 'stable', '## Why this module exists

You almost certainly already use AI. You''ve probably asked something to tidy up a job description, turn a page of interview scrawl into a debrief a hiring manager can read, soften a rejection email, or explain a benefits provision in language an employee will actually understand. So opening a course with "what is AI?" is a strange move. The answer is on your screen already.

But there is a difference between using this technology and understanding what happens when you use it, and most people skip the second part. That skip is where the Risk-stage problems come from. People without a working mental model tend to land in one of two places. Some treat it as a search engine that returns true facts — it is not, and it does not. Others treat it as a colleague with intentions, judgment, and a stake in the outcome — it has none of those, not in the way you mean. Both framings will get you in trouble, in different ways and on different timelines.

There''s a reason to care about this more in People work than in most functions. In sales, using AI carelessly produces a weak email. In People, it can produce a document that shapes someone''s livelihood — a performance write-up, a policy interpretation, a screening decision, an investigation summary — and it can produce that document fluently, confidently, and wrong. The gap between how good the output *sounds* and how good it *is* is exactly the gap this module exists to close.

This module gives you a third framing: accurate enough to be useful, simple enough to carry around under pressure. No mathematics, no philosophy, no diagrams of neural networks. Just a working account of what these systems do, where they come from, and what that means for how you use them.

**A note on your two roles.** As a People leader you will be asked to do two different things with AI: use it well in your own work, and eventually help other functions adopt it. Those are different jobs and they need different preparation. You cannot credibly lead a change you can''t perform, so this course is about the first one. The second gets its own course, later.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-objectives', 'ai101-m1', 20, 'callout', 'stable', '### Learning objectives

By the end of this module you should be able to:

1. Explain, in plain language, what people mean by "AI" today — and what they don''t.
2. Describe what a large language model actually does when you send it a message.
3. Recognize and use the working vocabulary: model, prompt, context window, token, knowledge cutoff, hallucination, agent.
4. Articulate why data — both what the model was trained on and what you hand it — determines the quality of what you get back.
5. Predict, before you begin a task, whether AI is likely to do it well.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l1-intro', 'ai101-m1', 30, 'prose', 'stable', '## Lesson 1 · What we mean when we say "AI"

The word is doing far too much work. People use it for the résumé screener in the ATS, the sentiment scoring on your engagement survey, ChatGPT, the anomaly flag in payroll, and the menacing robot from a film — often in the same meeting. That''s part of why two reasonable people can have wildly different reactions to "we should use more AI." They''re not discussing the same thing.

Here''s the cut that clears it up. **"AI" is a category, not a technology.** Inside that category sit many different systems built in different ways for different purposes. The kind currently reshaping knowledge work — and the kind this course is mostly about — is a specific type called a **large language model**, or LLM. When a colleague says "I used AI to write this," they almost always mean they used an LLM.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l1-lineup', 'ai101-m1', 40, 'prose', 'volatile', 'The LLMs you''ll encounter most: Claude, from Anthropic. ChatGPT, from OpenAI, built on the GPT family. Gemini, from Google. Those are the consumer-facing names; underneath, they''re the same general kind of system — software trained on an enormous quantity of text that reads and produces human-like language.', '["model-lineup"]', '2026-08-04');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l1-hrstack', 'ai101-m1', 50, 'prose', 'stable', '### The part that matters specifically for People work

Much of the "AI" already sitting in your HR technology stack is **not** an LLM. Résumé matching and ranking, candidate scoring, attrition risk models, engagement sentiment classification, payroll anomaly detection, scheduling optimization — most of these are older machine-learning techniques doing statistical classification or scoring. Some vendors have since layered an LLM on top for the chat interface while the underlying scoring engine remains what it always was.

This distinction is not pedantry, for three reasons:

- **It changes what questions to ask a vendor.** "Is this a language model or a scoring model?" gets you further than "is this AI?", which every vendor now answers yes to.
- **It changes the failure mode.** A scoring model fails by being systematically biased against a group. A language model fails by fabricating. Those need different controls.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l1-regulatory', 'ai101-m1', 60, 'prose', 'volatile', '- **It changes your regulatory exposure.** Regulation in this area tends to attach to *automated decision-making about people* rather than to a technology label. A scoring model that ranks candidates is squarely in scope under rules like NYC''s Local Law 144 and the EU AI Act''s treatment of employment as high-risk. An LLM you use to redraft a job posting generally isn''t. Confusing the two means you either over-comply on harmless uses or under-comply on the ones that count. *Verify current specifics with counsel — this area moves.*', '["employment-regulation","eu-ai-act"]', '2026-08-04');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l1-close', 'ai101-m1', 65, 'prose', 'stable', 'So: when this course says "AI" without qualification, it means a large language model. Software that takes text in and produces text out, using patterns learned from a very large quantity of text it was trained on.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l1-try', 'ai101-m1', 70, 'try_this', 'stable', '### Try this — 2 minutes

1. List every place you used AI at work last week. Be specific: not "ChatGPT," but "I had it rewrite the internal comms note about the benefits change."
2. For each one, ask: was that an LLM, or was it a scoring or matching feature inside a tool I already use?
3. Then look at your ATS or HRIS. Find one feature marketed as AI and decide which kind it is.

You won''t be certain on all of them. That uncertainty is useful information — it tells you where you''d have to ask a vendor a direct question.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l1-sort', 'ai101-m1', 80, 'exercise', 'stable', '{"type":"sorting","title":"Calibration exercise — Where does AI actually help?","intro":"Ten minutes. This is the most important exercise in the module.\n\nBelow are fifteen tasks a People team might plausibly hand to an LLM. Sort each into **does this well**, **does this partly — needs verification**, or **does this badly — don''t**.\n\nNothing reveals until all fifteen are committed — an unscored guess teaches nothing."}', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l2-mechanism', 'ai101-m1', 90, 'prose', 'stable', '## Lesson 2 · What an LLM actually does, in plain English

The mechanism reduces to one sentence:

> **A large language model is software that, given some text, predicts what text should come next — one small piece at a time.**

Everything else is detail. But the detail is where the practical consequences live, so it''s worth two minutes.

### The training step

Before you type anything, the model has been trained. Training means it was shown an enormous quantity of text — books, articles, websites, code, transcripts, forums — and learned the statistical patterns of how language works. Not memorized. Learned. It picked up that "we regret to inform you that your application" is very likely followed by something other than "congratulations." It picked up grammar, register, tone, structure, factual associations, and a few thousand other regularities, all from patterns in text.

That training happened before you arrived. When you open the tool, the model is already finished. You are not teaching it anything during your conversation, and Lesson 4 explains why that matters more than it sounds like it should.

### The prediction step

Now you type. The model takes your message plus everything else in the conversation and asks one narrow question: *given everything I''ve seen so far, what''s the most likely next piece of text?* It picks a piece, appends it, and asks again. And again, until it stops.

It is not drafting a complete answer and then writing it out. It is not retrieving an answer from a database. It is generating text one fragment at a time, where each fragment is the most probable continuation of everything before it.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l2-try', 'ai101-m1', 100, 'try_this', 'stable', '### Try this — 3 minutes

1. Open your AI tool.
2. Send exactly: *"Tell me a short, surprising fact about octopuses, then explain how you know it."*
3. Read the answer.
4. Follow up: *"How did you generate that? Walk me through what actually happened, step by step."*

You''ll get the model''s own account of itself. Notice the vocabulary — probability, training data, patterns. Notice what it never says: *"I looked it up."* *"I checked a source."* Because neither happened.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l2-frustrations', 'ai101-m1', 110, 'prose', 'stable', '### Why this explains almost everything that will frustrate you

**Why it sounds confident about wrong things.** The model isn''t checking facts as it writes; it''s producing statistically likely text. Sometimes statistically likely text is also true. Sometimes it isn''t. In human writing, confidence and correctness are loosely coupled — someone who sounds certain usually has reason to be. That coupling does not exist here. M6 is entirely about this.

**Why the same prompt gives different answers.** There''s a small amount of randomness in how each next piece gets chosen. Without it, every response would be identical and mechanical. With it, asking twice gives you two drafts. That''s not a malfunction — it''s why re-running a prompt is a legitimate technique rather than a sign something broke.

**Why context changes everything.** Because prediction runs on everything the model has been given, more relevant material means better predictions. A vague prompt leaves the model predicting from almost nothing. A prompt carrying role, task, context, and format narrows the prediction toward what you actually wanted. M5 covers this properly.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l2-memory', 'ai101-m1', 120, 'prose', 'volatile', '**Why it doesn''t remember you.** Each conversation typically starts fresh. The model has no memory across sessions unless something was specifically built to give it one. Memory features have become common across the major tools, but they vary in what they retain and for how long, and the default is often off. Never assume; check what your specific tool does.', '["memory-features"]', '2026-08-04');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l2-honest', 'ai101-m1', 130, 'prose', 'stable', '### The honest part: nobody fully understands the inside

Even the people who build these systems don''t fully understand how they work internally. Training produces a model with billions of parameters that encode the learned patterns, and those parameters aren''t human-readable. Anthropic has published interpretability research — techniques for tracing what happens inside a model as it responds — precisely because the internals aren''t otherwise visible, including to them.

What that research has surfaced is genuinely interesting. There''s evidence models do more than blind word-by-word prediction in some cases: planning ahead toward a rhyming word before starting a line, for instance, or representing concepts in a shared space that spans languages. There''s also evidence that when a model explains its reasoning, the explanation doesn''t always match what actually happened internally.

You don''t need to retain any of that. It''s here because it pushes back on both of the confident positions you''ll hear in meetings — *"it''s just autocomplete"* (mechanically defensible, underestimates what falls out of the mechanism) and *"it genuinely thinks"* (wrong in a different direction). The useful stance sits between: a powerful pattern-matcher trained on a vast amount of human text, which often produces startlingly good output and has failure modes worth building habits around.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l3-vocab-a', 'ai101-m1', 140, 'prose', 'stable', '## Lesson 3 · The vocabulary, demystified

You''ll keep hearing these. Don''t memorize them — read through once and notice the shape of each. They recur throughout the course.

**Model.** The trained system itself. When someone says "the model did something strange," they mean the underlying AI, not the website they used to reach it. Models come in different sizes; larger ones are generally more capable, slower, and more expensive to run.

**Prompt.** What you send — your text, plus any instructions, context, or attached material. Your prompt is the single largest lever you have on output quality. M5 is entirely about this.

**Context window.** How much text the model can hold in view at once when responding: your message, the conversation so far, and anything attached. It''s finite. When it fills, earlier material effectively drops out of view — which is why long conversations start to feel like the model forgot something, and why pasting in a 90-page handbook can crowd out your actual question.

**Token.** The unit models process text in — roughly a word or word-fragment. Mostly this matters for two reasons: context windows are measured in tokens, and pricing is usually per token. M3 covers the economics.

**Training data.** The text the model learned from. It shapes everything: what the model handles well, what it fumbles, what registers it can write in, and what biases it carries.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l3-cutoff', 'ai101-m1', 150, 'prose', 'volatile', '**Knowledge cutoff.** The date past which the model wasn''t trained on new information. Most current tools pair the model with web search to compensate, but the underlying model still has a cutoff. It''s why asking about yesterday''s news, without search enabled, produces something fluent and useless.', '["knowledge-cutoff","search-features"]', '2026-08-04');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l3-vocab-b', 'ai101-m1', 160, 'prose', 'stable', '**Hallucination.** When a model produces something confident, plausible, and wrong or invented. The single most important failure mode to understand, and the one with the sharpest consequences in People work. M6 is devoted to it.

**Agent.** A model configured to take actions rather than only respond — browsing, sending, updating a record, running code — within whatever permissions it''s been given. You don''t need to work with agents at this level. Just know the word means *an AI system that does things*, not one that only talks.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l3-multimodal', 'ai101-m1', 170, 'prose', 'volatile', '**Multimodal.** Models that handle more than text — images, audio, documents. Current frontier models are multimodal; you can paste a screenshot of an org chart or attach a PDF policy and ask questions about it. Same mechanics underneath, wider set of inputs.', '["multimodal-capabilities"]', '2026-08-04');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l3-try', 'ai101-m1', 180, 'try_this', 'stable', '### Try this — 3 minutes

Open the product page of one HR tool your team uses that advertises AI features. Read the claims and answer three questions:

1. Is this a language model, a scoring or matching model, or both?
2. What data was it trained on — theirs, yours, or unstated?
3. Does it make or influence a decision about a person?

If you can''t answer all three from the page, you''ve just written your first three vendor questions. That''s the exercise working.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l4-training', 'ai101-m1', 190, 'prose', 'stable', '## Lesson 4 · Why data is the whole game

If one thing survives from this module, make it this: **AI is a data problem before it is anything else.** What you get out is determined, almost entirely, by two things — what the model was trained on, and what you hand it in the moment.

### Training data shapes the model

The model only handles well what it saw patterns for. Well-represented topics get handled well. Sparse ones get hedging, vagueness, or invention.

Practical consequences:

- A model trained mostly on English performs better in English, even when it produces other languages competently.
- A model trained on public text has never seen your handbook, your HRIS, your comp bands, your Slack, your investigation files, or your board deck. It cannot draw on what it never saw.
- **All training data carries bias, and models reproduce it.** In most functions that''s an abstract concern. In People work it is not. A model asked to evaluate, rank, or characterize people can reproduce patterns present in its training text — and in an employment context, that is the mechanism by which adverse impact happens. This is why the delegation heuristic ends with *"it must not make decisions about people."*

The habit to build: before asking, form a rough view of whether this is the kind of thing the model would have seen a great deal of. *"Rewrite this clunky paragraph"* — enormous quantities of training data. *"What''s our policy on carryover PTO"* — none whatsoever. The first is squarely in the model''s competence. The second, asked cold, produces something fluent, confident, and made up.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l4-recency', 'ai101-m1', 200, 'prose', 'volatile', 'One more practical consequence: a model trained through a given date is unreliable about anything after it, unless you supply fresh information or search is enabled.', '["knowledge-cutoff"]', '2026-08-04');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l4-supply', 'ai101-m1', 210, 'prose', 'stable', '### The data you supply

The second kind is what you give it — your prompt, your attachments, the context you establish. Because the model knows only its training plus what''s in the current conversation, the material you supply is your only channel for getting your specific world into the picture.

Ask for a summary of your engagement survey results without pasting the results, and the model will produce a survey summary. A generic, plausible, entirely fictional one. Paste the actual comments and you get real analysis. Same model, same prompt structure, completely different output — because the data changed.

This is why prompting is far more about **information** than about clever phrasing. The wording matters, and M5 will make you better at it, but wording is downstream of whether the model has what it needs.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l4-paste', 'ai101-m1', 220, 'prose', 'stable', '### A note on what you paste

People data is the most sensitive material in most organizations, which makes "what can I put in here" a sharper question for you than for almost any other function. Employee records, health information, investigation notes, compensation data, and anything identifying a named individual sit at the top of that gradient.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l4-agreements', 'ai101-m1', 230, 'prose', 'volatile', 'The answer depends entirely on which tool you''re using and under what agreement — an enterprise deployment with a data processing agreement is a different situation from a personal account on a consumer tier. Find out which one you''re in before you paste, not after. Your security or legal team has this answer. If nobody does, that gap is itself worth raising.', '["data-agreements"]', '2026-08-04');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l4-close', 'ai101-m1', 240, 'prose', 'stable', 'M8 returns to this when we discuss what you own. For now: data is what makes the system work, and the data you supply is the part you control.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-l4-try', 'ai101-m1', 250, 'try_this', 'stable', '### Try this — 3 minutes

1. Pick one thing you did last week that involved AI, or could have.
2. Ask: what did the model need to know that it couldn''t have known on its own?
3. If you didn''t supply that, what did it fill the gap with?

The question *"what does this model not know that I''d have to give it?"* is the single most useful habit in this course. It''s the seed of good prompting and the seed of good judgment about when not to bother.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-takeaways', 'ai101-m1', 260, 'takeaways', 'stable', '## Key takeaways

- **"AI" is a category.** The kind reshaping your work is a large language model. Much of the AI already in your HR stack is something else — usually a scoring or matching model — and the distinction changes the failure mode, the vendor questions, and the regulatory exposure.
- **An LLM predicts the next piece of text, one piece at a time,** based on everything it''s seen. It is not retrieving, not verifying, and not reasoning the way a person does — even when the output looks like reasoning.
- **Confidence and correctness are decoupled** in a way they aren''t in human writing. This is the root of hallucination and the reason fluent output deserves more scrutiny, not less.
- **The model has never seen your organization.** Not your handbook, your data, your history, or your decisions. Anything requiring that knowledge must be supplied by you or it will be invented.
- **All training data carries bias, and in People work that''s not abstract** — it''s the mechanism behind adverse impact.
- **The delegation heuristic:** AI does well when you supply the material and ask for transformation; badly when the task needs organizational knowledge it was never given; and it must not make decisions about people.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1-activity-link', 'ai101-m1', 270, 'exercise', 'stable', '{"type":"activity_link","title":"Applied activity — Testing the Edges","blurb":"Three short conversations with your AI tool, each built to expose a different property of the system, then a 250–350 word reflection. Graded against a four-dimension rubric with per-dimension feedback. Free unlimited resubmission.","estMinutes":"20–25"}', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1a-intro', 'ai101-m1-activity', 10, 'prose', 'stable', '## Applied activity — "Testing the Edges"

**Time:** 20–25 minutes · **Submit:** a record of three conversations plus a 250–350 word reflection · **Graded against the rubric below.** Score doesn''t matter. Doing the work is where the learning lands.

Have three short conversations with your AI tool. Each is built to expose a different property of the system. Then write a short reflection on what you noticed.

This is not about getting good answers. It''s about watching the thing behave so you build real intuition for what it is.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1a-conv1', 'ai101-m1-activity', 20, 'prose', 'stable', '### Conversation 1 — Where it''s strong

Pick a subject you know well: an area of People practice you''ve worked in for years, a policy you wrote, a process you own. Ask a substantive question. Read the answer critically — you''re one of the few people who can actually judge it. Then ask one follow-up that pushes deeper.

*Notice:* What does it handle well? Where does it sound like it genuinely understands? Where does it produce something that reads correctly but that you know is thin?', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1a-conv2', 'ai101-m1-activity', 30, 'prose', 'stable', '### Conversation 2 — Where it might fabricate

**Predict first.** Before you send anything, write down: *how likely is it that this answer contains something invented?* Give a percentage — there''s a field for it below.

Then ask for something specific and hard to verify. Options that work:

- A statistic about employment practice with a source citation
- What a specific named regulation requires in a specific jurisdiction
- Details about a small organization you know well
- A quotation from a specific page of a specific book

Now check it. Actually check it — follow the citation, look up the regulation, verify the number.

*Record:* your prediction, what actually happened, and how far off you were.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1a-conv3', 'ai101-m1-activity', 40, 'prose', 'stable', '### Conversation 3 — Where it can''t know

Ask something about your own organization that the model was never given. Your parental leave provision. Why your last engagement survey moved. Which of your roles takes longest to fill.

Watch carefully. Does it refuse? Hedge? Ask you for context? Or does it produce something fluent, specific, and fabricated? Then paste in the actual material and ask again.

*Notice:* the difference between the two answers is the entire lesson of Lesson 4.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1a-reflection', 'ai101-m1-activity', 50, 'prose', 'stable', '### The reflection — 250–350 words

Address all of:

- One thing the model did better than you expected
- One thing it did worse
- Your calibration: what you predicted in Conversation 2, what happened, and which direction you were wrong in
- One habit you''ll change on Monday, stated concretely enough that someone could check whether you did it', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1a-rubric', 'ai101-m1-activity', 60, 'table', 'stable', '### Rubric — 20 points

| Dimension | 5 points |
|---|---|
| **Engagement with all three conversations** | All three run, with actual transcripts or faithful accounts. Follow-ups asked. Real subject matter, not placeholder queries. |
| **Observation of mechanics** | The reflection connects what was observed to how the system works — prediction, training data, context — rather than only reporting what it said. |
| **Calibration** | A prediction was made *before* Conversation 2, compared honestly afterward, and the direction of error is named. Accuracy isn''t scored; honesty and specificity are. |
| **Practical insight** | The habit named is concrete, tied to actual work, and checkable. Not "I''ll be more careful." |', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1micro-core', 'ai101-m1-micro', 10, 'prose', 'stable', '## Module 1 in two minutes

**"AI" is a category, not a technology.** The kind reshaping your work is a large language model (LLM): software that, given some text, predicts what should come next — one small piece at a time. It is not searching, not looking things up, and not reasoning like a colleague, even when it sounds like one. Much of the "AI" already in your HR stack is something else entirely — a scoring or matching model — and the distinction changes the failure mode, the vendor questions, and the regulatory exposure.

**Confidence and correctness are decoupled.** The model produces statistically likely text. Sometimes likely is also true; sometimes it isn''t. In human writing, someone who sounds certain usually has reason to be — that coupling does not exist here. Fluent output deserves more scrutiny, not less, and in People work a fluent, wrong document can shape someone''s livelihood.

**The model has never seen your organization.** Not your handbook, your comp bands, your survey data, your investigation files. Anything that requires that knowledge must be supplied by you in the conversation — or it will be invented, fluently, with no signal that it''s invented.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1micro-heuristic', 'ai101-m1-micro', 20, 'callout', 'stable', '### The delegation heuristic

AI does well when you supply the material and ask for transformation. It does badly when the task needs organizational knowledge it was never given. And it must not make decisions about people — regardless of how good the output looks.', NULL, '2026-07-28');
INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at) VALUES ('m1micro-habit', 'ai101-m1-micro', 30, 'prose', 'stable', '**The one habit to build:** before any task, ask *"what does the model not know that I''d have to give it?"* That single question is the seed of good prompting and of good judgment about what to hand over at all.', NULL, '2026-07-28');
