// Generates seed/seed.sql from the JSON content files.
// Passcodes are hashed here (PBKDF2-SHA256, 100k iterations, per-code salt) so
// only hashes ever reach the database. Override codes via env:
//   DEMO_CODES='omnissa:OMNISSA-101:Reviewer 1,verdant:VERDANT-DEMO:Theming proof'
// A fourth field maps a code to a short course from content/short-courses.json
// (no fourth field = the full course):
//   DEMO_CODES='omnissa:HRBP-SPRINT:HRBP pilot:sc-hrbp-sprint'
//
// Module content seeds from packages under content/modules/<moduleId>/:
//   blocks.json  activity.json  micro.json      -> fd_content_block
//   sorting.json choice.json rubric.json knowledge-check.json -> fd_exercise (keys stay server-side)
import { webcrypto as crypto } from 'node:crypto';
import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => JSON.parse(readFileSync(join(root, p), 'utf8'));

const ITERATIONS = 100_000;

async function hashCode(code) {
  const salt = crypto.getRandomValues(new Uint8Array(16));
  const key = await crypto.subtle.importKey('raw', new TextEncoder().encode(code.normalize('NFKC')), 'PBKDF2', false, ['deriveBits']);
  const bits = await crypto.subtle.deriveBits({ name: 'PBKDF2', hash: 'SHA-256', salt, iterations: ITERATIONS }, key, 256);
  const b64 = (buf) => Buffer.from(buf).toString('base64');
  return `pbkdf2$${ITERATIONS}$${b64(salt)}$${b64(bits)}`;
}

const q = (v) => (v === null || v === undefined ? 'NULL' : `'${String(v).replace(/'/g, "''")}'`);
const now = new Date().toISOString();

const brands = [read('content/brands/omnissa.json'), read('content/brands/verdant.json')];
const { modules } = read('content/modules.json');
const { shortCourses } = read('content/short-courses.json');

const codesSpec = (
  process.env.DEMO_CODES ??
  [
    'omnissa:OMNISSA-101:Reviewer 1 · Omnissa',
    'verdant:VERDANT-DEMO:Theming proof',
    'omnissa:HRBP-SPRINT:HRBP short course:sc-hrbp-sprint',
    'omnissa:TD-SPRINT-26:Talent Development short course:sc-talent-dev-sprint',
    'omnissa:AI101-BASICS:AI Foundations short course:sc-ai-foundations',
  ].join(',')
)
  .split(',')
  .map((entry) => {
    const [brandSlug, code, label, shortCourseId] = entry.split(':');
    return { brandSlug, code, label, shortCourseId: shortCourseId || null };
  });

const moduleIds = new Set(modules.map((m) => m.id));
for (const sc of shortCourses) {
  const missing = sc.moduleIds.filter((id) => !moduleIds.has(id));
  if (missing.length) throw new Error(`short course ${sc.id} names modules that don't exist: ${missing.join(', ')}`);
}
const shortCourseIds = new Set(shortCourses.map((s) => s.id));
for (const { code, shortCourseId } of codesSpec) {
  if (shortCourseId && !shortCourseIds.has(shortCourseId)) throw new Error(`code ${code} maps to unknown short course ${shortCourseId}`);
}

const lines = [];
lines.push('-- Generated by scripts/generate-seed.mjs — do not edit by hand.');
for (const t of ['fd_content_block', 'fd_exercise', 'fd_module', 'fd_brand', 'fd_access_code', 'fd_short_course']) lines.push(`DELETE FROM ${t};`);

for (const b of brands) {
  // profile_json carries the optional company profile (e.g. provisioned aiTools).
  const profile = b.aiTools?.length ? q(JSON.stringify({ aiTools: b.aiTools })) : 'NULL';
  lines.push(
    `INSERT INTO fd_brand (slug, name, tokens_json, voice_json, profile_json, created_at) VALUES (${q(b.slug)}, ${q(b.name)}, ${q(JSON.stringify(b.tokens))}, ${q(JSON.stringify(b.voice))}, ${profile}, ${q(now)});`,
  );
}

// createdAt comes from the content file, not the clock: short-course rows sit
// inside the publish workflow's "is the committed seed current?" diff, and a
// generation timestamp would make that check fail on any day but the one the
// seed was committed.
for (const sc of shortCourses) {
  lines.push(
    `INSERT INTO fd_short_course (id, brand_slug, label, blurb, role_id, module_ids_json, diagnostic_json, created_at) VALUES (${q(sc.id)}, ${q(sc.brandSlug)}, ${q(sc.label)}, ${q(sc.blurb ?? null)}, ${q(sc.roleId ?? null)}, ${q(JSON.stringify(sc.moduleIds))}, ${q(sc.diagnostic ? JSON.stringify(sc.diagnostic) : null)}, ${q(sc.createdAt ?? now.slice(0, 10))});`,
  );
  console.log(
    `short course seeded → ${sc.id} · ${sc.moduleIds.length} modules · diagnostic: ${sc.diagnostic ? `${sc.diagnostic.items.length} items` : 'none'}`,
  );
}

for (const { brandSlug, code, label, shortCourseId } of codesSpec) {
  const hash = await hashCode(code);
  const id = crypto.randomUUID();
  lines.push(
    `INSERT INTO fd_access_code (id, brand_slug, code_hash, label, max_uses, uses, expires_at, active, short_course_id) VALUES (${q(id)}, ${q(brandSlug)}, ${q(hash)}, ${q(label)}, NULL, 0, NULL, 1, ${q(shortCourseId)});`,
  );
  console.log(`access code seeded → brand=${brandSlug} label=${JSON.stringify(label)} code=${code} course=${shortCourseId ?? 'full'}`);
}

for (const m of modules) {
  lines.push(
    `INSERT INTO fd_module (id, course_id, ordinal, title, blurb, status, est_minutes, prereq_json) VALUES (${q(m.id)}, ${q(m.courseId)}, ${m.ordinal}, ${q(m.title)}, ${q(m.blurb)}, ${q(m.status)}, ${m.estMinutes}, ${q(m.prereqs?.length ? JSON.stringify(m.prereqs) : null)});`,
  );
}

const insertBlock = (b) =>
  lines.push(
    `INSERT INTO fd_content_block (id, module_id, ordinal, kind, layer, body, depends_on, reviewed_at, variant) VALUES (${q(b.id)}, ${q(b.moduleId)}, ${b.ordinal}, ${q(b.kind)}, ${q(b.layer)}, ${q(b.body)}, ${q(b.dependsOn ? JSON.stringify(b.dependsOn) : null)}, ${q(b.reviewedAt)}, ${q(b.variant ?? null)});`,
  );

const packagesDir = join(root, 'content', 'modules');
const packages = readdirSync(packagesDir, { withFileTypes: true })
  .filter((e) => e.isDirectory())
  .map((e) => e.name)
  .sort();

for (const moduleId of packages) {
  const dir = join('content', 'modules', moduleId);
  let blockCount = 0;
  for (const file of ['blocks.json', 'activity.json', 'micro.json']) {
    if (!existsSync(join(root, dir, file))) continue;
    const items = read(join(dir, file));
    items.forEach(insertBlock);
    blockCount += items.length;
  }
  const exercises = [];
  for (const [file, kind] of [
    ['sorting.json', 'sorting'],
    ['choice.json', 'choice'],
    ['rubric.json', 'rubric'],
    ['knowledge-check.json', 'knowledge_check'],
  ]) {
    if (!existsSync(join(root, dir, file))) continue;
    const payload = read(join(dir, file));
    lines.push(
      `INSERT INTO fd_exercise (id, module_id, kind, payload_json, reviewed_at) VALUES (${q(`${moduleId}-${kind}`)}, ${q(moduleId)}, ${q(kind)}, ${q(JSON.stringify(payload))}, ${q(payload.reviewedAt ?? now.slice(0, 10))});`,
    );
    exercises.push(kind);
  }
  console.log(`package ${moduleId}: ${blockCount} blocks · exercises: ${exercises.join(', ') || 'none'}`);
}

mkdirSync(join(root, 'seed'), { recursive: true });
writeFileSync(join(root, 'seed', 'seed.sql'), lines.join('\n') + '\n');
console.log(`wrote seed/seed.sql (${lines.length} statements)`);
